[package]
name = "rustiplan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.2"
fermi = "0.3.0"
lazy_static = "1.4.0"
pest = "2.5.3"
pest_derive = "2.5.4"
